FROM linuxserver/code-server:latest
RUN sed -i "s/http:\/\/archive.ubuntu.com/https:\/\/mirrors.ustc.edu.cn/g" /etc/apt/sources.list && apt update && sudo apt upgrade -y &&\
    apt-get install -y iproute2 dnsutils wget zsh build-essential manpages-dev golang pip cargo rsync nodejs npm cron fonts-wqy-zenhei language-pack-zh-hans inetutils-ping knot-dnsutils gdb && curl https://gitlab.com/volian/volian-archive/-/raw/main/install-nala.sh | bash && echo "**** clean up ****" && \
  apt-get clean && \
  rm -rf \
    /config/* \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* && chsh -s /bin/zsh && chsh -s /bin/zsh abc