#!/usr/bin/with-contenv bash

# shellcheck shell=bash
set -euo pipefail

umask "${UMASK:-022}"

apache_args=(
    -f /config/httpd.conf
    -DFOREGROUND
)

auth_mode=${WEBDAV_AUTH:-basic}
if [[ ${auth_mode,,} == none ]]; then
    apache_args+=( -DWEBDAV_NO_AUTH )
fi

exec 2>&1
exec s6-notifyoncheck \
    -d \
    -n 300 \
    -w 1000 \
    -c "curl -fs -o /dev/null http://127.0.0.1/.webdav-health" \
    /usr/sbin/apache2 "${apache_args[@]}"
