DocumentRoot "/data"
<Directory "/data">
    Dav On
    AllowOverride None
    Options Indexes
    IndexOptions FancyIndexing HTMLTable VersionSort NameWidth=* Charset=UTF-8
    LimitRequestBody 0

    <IfDefine WEBDAV_NO_AUTH>
        Require all granted
    </IfDefine>

    <IfDefine !WEBDAV_NO_AUTH>
        AuthType Basic
        AuthName "WebDAV"
        AuthBasicProvider file
        AuthUserFile "/config/auth/users.htpasswd"
        Require valid-user
    </IfDefine>

    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "no-referrer"
</Directory>
