name: sync readme

on: 
  push:
    branches:
      - master
    paths:
      - "README.md"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: sync vergilgao/mdc
          uses: ms-jpq/sync-dockerhub-readme@v1
          with:
            username: vergilgao
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: vergilgao/mdc
            readme: README.md
        - name: sync vergilgao/avdc
          uses: ms-jpq/sync-dockerhub-readme@v1
          with:
            username: vergilgao
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: vergilgao/avdc
            readme: README.md
