# Version 2.0
FROM linuxserver/jellyfin:10.8.13
RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list && apt update  && apt install -y fonts-noto-cjk-extra fonts-wqy-zenhei && echo "**** clean up ****" && \
  apt-get clean && \
  rm -rf \
    /config/* \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* 